Feat/deliverable2
franciscotsh/wa-react-2021-q4-capstone-project pull request #2
Opened 2021-10-24 19:16 UTC by franciscotsh

Still missing classname change from dom, gonna work on it this week

2021-10-25 23:27 UTC, luismichel commented on src/components/categoryCarousel/CategoryCarousel.js
> +                key={'cat_radio_'+index}
Usa mejor un valor que venga en `ele`, el key que escogiste te da el mismo resultado que si usas solamente `index`. Checa este artículo donde explican por qué pasa esto https://reactjs.org/docs/lists-and-keys.html#keys

2021-10-25 23:27 UTC, luismichel commented on src/components/productGrid/ProductGrid.js
> +    for (let i = 0; i < limit; i++) {
Usa mejor `Array.prototype.map` y `Array.prototype.slice` para la paginación, es más fácil de leer y te ahorra muchos posibles errores que pueden generarse de iterar "manualmente". https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

Solo tendrías que guardar los valores de `limit` y tal vez un `start`, entonces podrías hacer algo como esto
```javascript
products
  .slice(start, limit)
  .map(product => {
    return (<div><span className="p-name">{product.data.name}</span></div>); // simplificando tu markup
  });
```
Nota que `products` nunca es mutado y puedes hacer más cosas con todos los productos.

2021-10-25 23:27 UTC, luismichel commented on src/components/productGrid/ProductGrid.js
> +                      categories.find(
Te recomendaría usar `Array.prototype.reduce` para procesar los datos de categorías y reducirlas a una estructura que sea más fácil de utilizar. Podrías crear una función que te reduzca los datos a algo como esto:

```
{
  "YWHx-xIAAC0Ayj7i": {
    "name": "Bed & Bath",
    "main_image": {
      "dimensions": {
        "width": 621,
        "height": 398
      },
      "alt": "Bath",
      "copyright": null,
      "url": "https://images.prismic.io/wizeline-academy/5df875b5-3e43-4cf0-97b9-06ed73ed6d9b_sanibell-bv-530lZQXMKGw-unsplash-web+%281%29.jpg?auto=compress,format&rect=0,24,1920,1231&w=621&h=398"
    }
  },
"YWHy0xIAACoAykKm": {
  "name": "Lighting",
  "main_image": {
      "dimensions": {
          "width": 621,
          "height": 398
      },
      "alt": "Lighting",
      "copyright": null,
      "url": "https://images.prismic.io/wizeline-academy/fdc4897a-c224-450f-9378-a39d2afaa7f6_zero-take-uLcBn2TsavU-unsplash-web+%281%29.jpg?auto=compress,format&rect=1,0,1919,1230&w=621&h=398"
    }
  },
...
}
```
Es un mapa donde el key es el id de la categoría y el valor es el objeto que está en `data` que te da el nombre, y los datos de la imagen de la categoría. Esta estructura simplificada te permitiría hacer cosas más sencillas aquí y en el futuro, tu código se simplificaría a hacer esto:

```javascript
...
<span className="p-company">
  { categories[product.data.category.id].name }
</span>
...
```
Esto es más legible, y el reducer lo puedes ejecutar fuera de la función render (ya que los datos no cambian). De otra manera, este `find` se ejecuta cada vez que se corre el `render` dentro de tu `for` de paginación.

2021-10-25 23:27 UTC, luismichel commented on src/components/productSideFilter/ProductSideFilter.js
> +    });
Puedes simplificar mucho esta lógica usando una combinación de `Array.prototype.filter` y `Array.prototype.includes`, por favor dale una checada y simplifica esta lógica para que está más fácil de leer.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2021-10-25 23:30 UTC, luismichel requested changes
Te dejé unos comments, cualquier duda, por favor contesta al comentario aquí y directamente en Slack también podemos verlo.

2021-10-26 19:43 UTC, franciscotsh commented on src/components/productGrid/ProductGrid.js
> +    for (let i = 0; i < limit; i++) {
Eso queria hacer pero no conocia el slice, lo aplicare!

2021-10-30 00:05 UTC, merged